/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f103x6.h"
#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103C6_UART_Driver.h"
#include "Stm32_F103C6_EXTI_Driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void clock_init()
{
	//Enable clock for GPIO
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();

	//Enable AFIO
	RCC_AFIO_CLK_EN();
}

uint16_t ch ;

 int main(void)
 {
	 UART_Config_t UART_Cfg;

	 clock_init();

	 UART_Cfg.USART_BAUDRATE = USART_BAUDRATE_115200;
	 UART_Cfg.USART_FLWCTRL = USART_FLWCTRL_NONE;
	 UART_Cfg.USART_IRQ_ENABLE = USART_IRQ_ENABLE_NONE ;
	 UART_Cfg.USART_PARITY = USART_PARITY_NONE;
	 UART_Cfg.USART_PAYLOAD_LENGTH = USART_PAYLOAD_LENGTH_8Bits;
	 UART_Cfg.USART_STOP = USART_STOP_ONE;
	 UART_Cfg.USART_MODE = USART_MODE_TX_RX;

	 MCAL_UART_Init(USART1, &UART_Cfg);

	 MCAL_UART_GPIO_Set_Pins(USART1);

	/*Loop Forever*/
	while (1)
		{
			MCAL_UART_ReceiveData(USART1, &ch , enable);
			MCAL_UART_SendData(USART1, &ch , enable);

		}

 }

